### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by andrewray** [ocaml-jupyter/jupyter-kernel#2]
Below is the equivalent toolset to `iocaml`.

* `ocaml-jupyter-kernel` an ocaml bytecode interpreter
* `js_of_ocaml-jupyter-kernel` ocaml bytecode interpreter compiled to javascript (needs some help from ocaml-jupyter-server to function properly)
* `ocaml-jupyter-server` webserver for jupyter kernels, built in ocaml.  Should run all projects derived from `jupyter-kernel` without modification.

Note; both kernels above would use the API in #1.

**Comment by c-cube** [comment]
Sounds like `ocaml-jupyter-server` (which is an alternative to the python-based `jupyter-notebook`, am I right?) should share the protocol definition (esp. the JSON spec file) with `jupyter-kernel`…

**Comment by andrewray** [comment]
You are right - ocaml-jupyter-server (or prefereably ojupyter!) is a webserver which replaces all the python stuff and includes a copy of the jupyter webpages, javascript and related cruft.

The iocaml-kernel ocamlfind library included all the json stuff, so that is needed.

**Comment by c-cube** [comment]
Right, we can continue to expose the protocol in there anyway, I guess. Personnally I just use the python stuff for now, but it's pretty cool that you can run a pure OCaml stack!

**Comment by slel** [comment]
I created pull request #7 to include a "Related work" section
in the README for this project. Could someone have a look?
Maybe expand it based on the issue description here?
