### ISSUE TITLE
kernel installation: doc + script

### ISSUE THREAD

**Issue by c-cube** [ocaml-jupyter/jupyter-kernel#3]
need some basic doc, and maybe a tiny ocaml script, to install a kernel description `foo.json` file in `~/.local/share/jupyter/kernels/`.

**Comment by tautologico** [comment]
For use with jupyter, the recommended way is to use kernelspec install, not to copy the kernelspec directly.

**Comment by c-cube** [comment]
So, `jupyter-kernelspec install`?

**Comment by tautologico** [comment]
Yes, or `jupyter kernelspec install`, same thing. We could provide a template kernelspec or a small script that builds the kernelspec for a kernel created with the library.
