### ISSUE TITLE
Should this be working currently?

### ISSUE THREAD

**Issue by fasiha** [ocaml-jupyter/jupyter-kernel#6]
Hi, sorry to ask this really dumb question, but if I run 
```
$ jupyter kernelspec install /path/to/jupyter-kernel --user --replace --name=ocaml
```
jupyter says, `Installed kernelspec ocaml in /Users/ahmed.fasih/Library/Jupyter/kernels/ocaml` but `ocaml` isn’t listed as an available kernel when I do
```
$ jupyter kernelspec list
```
or when I start a `jupyter notebook`. No errors are reported. Should this work currently? Thank you!

**Comment by c-cube** [comment]
Hum, the library doesn't come with an existing kernel (it's a library for writing kernels). We would like to use it in IOCaml but right now it's not ready, sorry :/

**Comment by slel** [comment]
@fasiha You might be interested in
- https://github.com/KKostya/simple_jucaml
- https://github.com/andrewray/iocaml

**Comment by fasiha** [comment]
Got it, thank you!
